language = {
    "en": "english",
    "nl": "dutch",
    "tr": "turkish",
    "es": "spanish",
}

vocabulary = {
    "en": "<en>Vocabulary",
    "nl": "<nl>Vocabulair",
    "es": "<es>Vocabulario",
    "tr": "<tr>Kelime hazinesi",
}

# the lists below contain the stories that have been checked for a specific language. 

# dutch 
files = [
    "everyday.txt",
    "my_daily_rhythm.txt",
    "taking_a_shower.txt",
    "shaving.txt",
    "grandmas_soup.txt",
    "a_walk_in_the_park.txt",
    "fire.txt",
    "flying.txt",
    "traffic.txt",
    "airport.txt",
    "swimming.txt",
    "elephant_and_friends.txt",
    "lion_and_mouse.txt",
    "elephant_and_mouse.txt",
    "cinderella.txt",
    "the_frog_prince.txt",
    "the_lost_ring.txt",
    "the_rabbit_and_the_tortoise.txt",
    "act_as_the_others.txt",
    "gulliver.txt",
    "ali_baba.txt",
    "the_shepherd_boy.txt",
    "the_kings_nightingale.txt",
    "the_moon_in_the_well.txt",
    "rabbit.txt",
    "nessie_the_monster_of_lochess.txt",
    "boys_will_be_boys.txt",
    "hercules.txt",
    "the_donkey_of_hodja.txt",
    "hodja_the_king.txt",
    "hodja_and_ox.txt",
    "hodja_and_the_scholar.txt",
    "the_hidden_treasure.txt",
    "sweet_quarrels.txt",
    "the_relatives_of_the_donkey.txt",
    "the_donkey_that_could_sing.txt",
    "romeo_and_juliet.txt",
    "the_fox_who_got_caught_in_the_tree_trunk.txt",
    "the_sleeping_beauty.txt",
    "half_the_reward.txt",
    "making_a_difference.txt",
    "birbal_shortens_the_road.txt",
    "birbal_turns_tables.txt",
    "a_wise_counting.txt",
    "question_for_question.txt",
    "birbals_sweet_reply.txt",
    "birbal_the_servant.txt",
    "birbal_the_wise.txt",
    "the_sharpest_sword.txt",
    "birbal_is_brief.txt",
    "the_well_dispute.txt",
    "list_of_blinds.txt",
    "a_handfull_of_answers.txt",
    "the_lazy_dreamer.txt",
    "siege_of_vienna.txt",
    "the_donkey_and_the_dog.txt",
    "the_donkey_and_the_cotton.txt",
    "the_cunning_bats.txt",
    "the_clever_bull.txt",
    "the_stone_cutter.txt",
    "the_sleepy_teacher.txt",
    "four_friends.txt",
    "the_dog_and_the_sparrow.txt",
    "the_lion_and_the_elephant.txt",
    "the_three_wisemen_and_the_camel.txt",
    "the_traveling_musicians.txt",
    "cinderella_2.txt",
    "the_princess_and_the_pea.txt",
    "the_emperors_new_clothes.txt",
    "the_little_mermaid.txt",
    "the_snow_queen.txt",
    "bluebeard.txt",
    "old_sultan.txt",
    "aladdin.txt",
    "the_ruined_man.txt",
    "the_enchanting_horse.txt",
    "the_monkey_advisor.txt",
    "arabian_nights_intro.txt",
    "the_merchant_and_the_genie.txt",
    "the_story_first_old_man.txt",
    "the_old_man_with_the_two_black_dogs.txt",
    "the_story_of_the_fisherman.txt",
    "the_story_of_greek_king.txt",
    "the_story_of_the_husband_and_the_parrot.txt",
    "the_enchanting_horse_2.txt",
    "prince_omar.txt",
    "the_story_of_the_punished_vizier.txt",
    "the_story_of_the_baked_head.txt",
]

turkish_to_dofiles = [
    "my_daily_rhythm.txt",
    "taking_a_shower.txt",
    "shaving.txt",
    "grandmas_soup.txt",
    "a_walk_in_the_park.txt",
    "cinderella.txt",
    "nessie_the_monster_of_lochess.txt",
    "the_donkey_of_hodja.txt",
    "hodja_the_king.txt",
    "hodja_and_ox.txt",
    "hodja_and_the_scholar.txt",
    "the_hidden_treasure.txt",
    "sweet_quarrels.txt",
    "the_relatives_of_the_donkey.txt",
    "romeo_and_juliet.txt",
    "the_fox_who_got_caught_in_the_tree_trunk.txt",
    "the_sleeping_beauty.txt",
    "half_the_reward.txt",
    "making_a_difference.txt",
    "birbal_shortens_the_road.txt",
    "birbal_turns_tables.txt",
    "question_for_question.txt",
    "birbals_sweet_reply.txt",
    "birbal_the_servant.txt",
    "birbal_the_wise.txt",
    "the_sharpest_sword.txt",
    "birbal_is_brief.txt",
    "the_well_dispute.txt",
    "list_of_blinds.txt",
    "the_lazy_dreamer.txt",
    "the_donkey_and_the_dog.txt",
    "the_donkey_and_the_cotton.txt",
    "the_cunning_bats.txt",
    "the_clever_bull.txt",
    "the_stone_cutter.txt",
    "the_sleepy_teacher.txt",
    "four_friends.txt",
    "the_dog_and_the_sparrow.txt",
    "the_lion_and_the_elephant.txt",
    "the_three_wisemen_and_the_camel.txt",
    "the_traveling_musicians.txt",
    "cinderella_2.txt",
    "the_princess_and_the_pea.txt",
    "the_emperors_new_clothes.txt",
    "the_little_mermaid.txt",
    "the_snow_queen.txt",
    "bluebeard.txt",
    "old_sultan.txt",
    "aladdin.txt",
    "the_ruined_man.txt",
    "the_enchanting_horse.txt",
    "the_monkey_advisor.txt",
    "arabian_nights_intro.txt",
    "the_merchant_and_the_genie.txt",
    "the_story_first_old_man.txt",
    "the_old_man_with_the_two_black_dogs.txt",
    "the_story_of_the_fisherman.txt",
    "the_story_of_greek_king.txt",
    "the_enchanting_horse_2.txt",
    "prince_omar.txt",
    "the_story_of_the_punished_vizier.txt",
    "the_story_of_the_baked_head.txt",
]

#print(len(files))
